name: Corevia

services:
  postgres:
    image: postgres:17
    container_name: Corevia-postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-Corevia}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - Corevia_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  server:
    profiles:
      - server
      - web
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: server
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: Corevia-server
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@postgres:5432/Corevia}
      CORS_ORIGIN: ${CORS_ORIGIN:-"http://localhost"}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-"supersecret"}
      BETTER_AUTH_URL: "http://server:3000"
      SESSION_SECRET: ${SESSION_SECRET:-"supersecret"}
    ports:
      - "3000:3000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
  migrate:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: migrate
    container_name: Corevia-migrate
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@postgres:5432/Corevia}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  seed:
    profiles:
      - seed
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: seed
    container_name: Corevia-seed
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@postgres:5432/Corevia}
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: ["yarn", "db:seed"]
  web:
    profiles:
      - web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        VITE_SERVER_URL: "http://localhost:3000"
    container_name: Corevia-web
    environment:
      NODE_ENV: production
      VITE_API_URL: "http://server:3000"
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: Corevia-drizzle-gateway
    restart: always
    ports:
      - "4983:4983"
    environment:
      PORT: 4983
      STORE_PATH: "/data"
      MASTERPASS: ${MASTERPASS:-devpass123}
    volumes:
      - drizzle-gateway:/data

volumes:
  Corevia_postgres_data:
  drizzle-gateway:
