name: Corevia

services:
  postgres:
    image: postgres:17
    container_name: Corevia-postgres
    environment:
      POSTGRES_DB: Corevia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - Corevia_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ../..
      dockerfile: ./apps/server/Dockerfile
    container_name: Corevia-backend
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/Corevia
      CORS_ORIGIN: http://localhost:5173
      BETTER_AUTH_SECRET: 0YyafjMCfnADbUK9zSlf7t8GVnS2u9bMutPMi6GPEqukTkd4QWf78iv1QpoJJOamLpxfJJq/L+0b7PwiCu4Xbg==
      BETTER_AUTH_URL: http://localhost:3000
      NODE_ENV: development
      SESSION_SECRET: your_session_secret
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  Corevia_postgres_data:
