name: Build and Push Docker Server Image to DigitalOcean

on:
  push:
    branches:
      - master
    paths:
      - "apps/server/**"
      - ".github/workflows/deployment_server.yml"

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      SERVER_VERSION: ${{ steps.get_version.outputs.SERVER_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get server version
        id: get_version
        run: echo "SERVER_VERSION=$(jq -r .version apps/server/package.json)" >> $GITHUB_ENV

  build-and-push:
    needs: get-version
    runs-on: ubuntu-latest
    env:
      SERVER_VERSION: ${{ needs.get-version.outputs.SERVER_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DIGITALOCEAN_REGISTRY_URL }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: |
            ${{ secrets.DIGITALOCEAN_REGISTRY_URL }}/corevia:server-latest
            ${{ secrets.DIGITALOCEAN_REGISTRY_URL }}/corevia:server-${{ env.SERVER_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./apps/server/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: [get-version, build-and-push]
    env:
      SERVER_VERSION: ${{ needs.get-version.outputs.SERVER_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_KUBE }}

      - name: Get kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig show corevia > ~/.kube/config

      - name: Update deployment image
        run: |
          kubectl set image deployment/corevia-server server=${{ secrets.DIGITALOCEAN_REGISTRY_URL }}/corevia:server-${{ env.SERVER_VERSION }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/corevia-server --timeout=120s
